language: node_js
node_js:
  - "8"
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn lint
  - yarn test
notifications:
  email: false
after_success:
  - yarn semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
